version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 10
    reviewers:
      - "Shatzii"
    assignees:
      - "Shatzii"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    groups:
      # Group React-related packages
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      # Group Next.js related packages
      nextjs:
        patterns:
          - "next"
          - "eslint-config-next"
          - "@next/*"
      # Group Radix UI packages
      radix-ui:
        patterns:
          - "@radix-ui/*"
      # Group TypeScript related packages
      typescript:
        patterns:
          - "typescript"
          - "@typescript-eslint/*"
          - "@types/*"
      # Group testing packages
      testing:
        patterns:
          - "vitest"
          - "@vitest/*"
          - "jsdom"
      # Group build tools
      build-tools:
        patterns:
          - "webpack"
          - "rollup"
          - "vite"
          - "esbuild"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    reviewers:
      - "Shatzii"
    assignees:
      - "Shatzii"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "automated"
