name: Publish GPT Docs
on:
  push:
    paths: ["gpt/docs/**", ".github/workflows/pages.yml"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare site
        run: |
          mkdir -p _site
          cp -r gpt/docs/* _site/
      - uses: actions/upload-pages-artifact@v3
        with:
          path: _site
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4